// layout
export { TheHeader } from './layout/TheHeader'
export { TheFooter } from './layout/TheFooter'
export { VoiceControlMenu } from './layout/VoiceControlMenu'
export { TextEditList } from './layout/TextEditList'
export { AvatarVoiceMenu } from './layout/AvatarVoiceMenu'
export { ProjectText } from './layout/ProjectText'
export { ProjectAvatarModal } from 'components/layout/ProjectAvatarModal'

// ui
export { VoiceController } from './ui/VoiceController'
export { ProjectSaveButton } from './ui/ProjectSaveButton'
export { TextPlayer } from './ui/TextPlayer'
export { AvatarVoicePlayer } from './ui/AvatarVoicePlayer'
export { ProjectNav } from './ui/ProjectNav'
export { AvatarSelector } from './ui/AvatarSelector'
export { ProjectList } from './ui/ProjectList'
export { NextButton } from './ui/NextButton'
export { VoiceUploadButton } from './ui/VoiceUploadButton'
export { ProjectRightNav } from './ui/ProjectRightNav'
export { SelectedAvatar } from './ui/SelectedAvatar'
export { SelectedVoiceOptions } from './ui/SelectedVoiceOptions'
export { AvatarSort } from './ui/AvatarSort'
export { AvatarBg } from './ui/AvatarBg'
export { TextEnterButton } from './ui/TextEnterButton'
export { PrevButton } from './ui/PrevButton'
export { RadioButton } from './ui/RadioButton'
export { MainSlider } from './ui/MainSlider'
export { VoicePreviewPlayer } from './ui/VoicePreviewPlayer'
export { ProjectTextModal } from './ui/ProjectTextModal'
export { ProjectRightMenu } from 'components/ui/ProjectRightMenu'
export { AvatarPreviewBtn } from './ui/AvatarPreviewBtn'
export { ProjectHistoryPlayer } from './ui/ProjectHistoryPlayer'
export { CompleteButton } from 'components/ui/CompleteButton'
export { ProjectVideoList } from 'components/ui/ProjectVideoList'
export { CreateProjectButton } from 'components/ui/CreateProjectButton'
export { Loading } from 'components/ui/Loading'
